version: "3.8"

services:
  web:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    command: go run main.go
    restart: always
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=talhaunal
      - POSTGRES_PASSWORD=talhaunal
      - POSTGRES_DB=talhaunal
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:7.0.10-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data
  react:
    build: ./client
    restart: always
    container_name: react_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres-db:
  redis-db:
