version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./main.go -b 0.0.0.0
    restart: always
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:7.0.10-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data


volumes:
  postgres-db:
  redis-db:
